"""SRT timeline health analysis — catch fabricated timings before they poison a run.

A subtitle file can be *textually* perfect and still be useless as training data,
because the timings were regenerated by a tool rather than measured against the
audio. That failure is invisible: every clip cuts successfully, QC passes, and
training converges to a model that drops words.

This module measures a timeline and refuses to guess. Three signatures matter:

1. **Quantized timestamps.** Real forced alignment emits fractional seconds
   (``00:01:23,417``). A file where every timestamp lands on a whole second was
   written by a program that was not looking at the waveform.

2. **Uniform inter-cue gaps.** Natural subtitles have gaps that vary with the
   speech. A constant gap repeated across thousands of transitions means the
   timeline was synthesised on a fixed grid.

3. **Speech inside the gaps.** The decisive one, and the only one that needs the
   audio: if the "silence" between cues is at speech loudness, the narration is
   continuous and every gap is being discarded by the segmenter — along with the
   tail of the text that describes it.

The h_tts_1 corpus tripped all three: integer timestamps, exactly 1.000s between
all 11,737 cue transitions, and gap windows measuring within 0.3 dB of the cue
windows. ~3.26 hours of speech were being thrown away, and each clip's text
described about a second more audio than the clip contained.

Typical use::

    report = analyze_timeline(parse_srt(path))
    if report.verdict != "natural":
        print(report.describe())
        cues = close_gaps(cues)      # reclaim the discarded speech
"""
from __future__ import annotations

from dataclasses import dataclass, field
from statistics import median, pstdev
from pathlib import Path

from hindi_tts_builder.utils.srt import SrtCue

# A timestamp is "on the grid" if it is this close to a whole second.
_GRID_EPS = 1e-6
# Inter-cue gaps whose spread is below this are considered machine-uniform.
_UNIFORM_GAP_STDEV = 0.002
# Below this many transitions, uniformity is coincidence rather than evidence.
_MIN_TRANSITIONS_FOR_UNIFORMITY = 20
# A uniform gap smaller than this is plausible natural cue padding, not a grid.
_SUSPICIOUS_GAP_SEC = 0.25

VERDICT_NATURAL = "natural"
VERDICT_QUANTIZED = "quantized"
VERDICT_SYNTHETIC = "synthetic_uniform_gap"
VERDICT_DEGENERATE = "degenerate"

#: Verdicts that mean the timeline must not be trusted for cutting audio.
UNTRUSTWORTHY = (VERDICT_QUANTIZED, VERDICT_SYNTHETIC, VERDICT_DEGENERATE)


@dataclass
class TimelineReport:
    """Everything measurable about an SRT timeline without reading the audio."""

    n_cues: int = 0
    # Fraction of cue boundaries landing exactly on a whole second.
    integer_ts_ratio: float = 0.0
    n_transitions: int = 0
    gap_median: float = 0.0
    gap_stdev: float = 0.0
    gap_min: float = 0.0
    gap_max: float = 0.0
    #: Total wall-clock seconds falling between cues — discarded by a naive cut.
    gap_total_sec: float = 0.0
    gaps_uniform: bool = False
    overlap_count: int = 0
    nonmonotonic_count: int = 0
    duration_median: float = 0.0
    duration_max: float = 0.0
    span_sec: float = 0.0
    # --- text, not timing: can this transcript be split into sentences at all? --
    #: Sentence terminators per 1000 characters. Healthy Hindi narration runs 15-18.
    terminators_per_1k: float = 0.0
    #: Mean terminators inside a single cue. Above ~1.2 means sentences are SHORTER
    #: than cues, so cue-level merging cannot reach most boundaries — only
    #: word-level timings can.
    terminators_per_cue: float = 0.0
    verdict: str = VERDICT_NATURAL
    warnings: list[str] = field(default_factory=list)

    @property
    def sentence_segmentable(self) -> bool:
        """False when the text carries too little punctuation to split on."""
        return self.terminators_per_1k >= 2.0

    @property
    def recommended_mode(self) -> str:
        """Which segmentation mode this file can actually support."""
        if not self.sentence_segmentable:
            return "none (unpunctuated - needs punctuation restoration or exclusion)"
        if self.terminators_per_cue > 1.2:
            return "aligned_words (sentences are shorter than cues)"
        return "sentence (cue merging can reach the boundaries)"

    @property
    def trustworthy(self) -> bool:
        return self.verdict not in UNTRUSTWORTHY

    @property
    def gap_fraction(self) -> float:
        """Share of the covered span that sits in inter-cue gaps."""
        return self.gap_total_sec / self.span_sec if self.span_sec > 0 else 0.0

    def describe(self) -> str:
        """Human-readable summary suitable for a CLI or a log."""
        lines = [
            f"timeline verdict: {self.verdict.upper()}"
            f"{'' if self.trustworthy else '  <-- DO NOT CUT AUDIO ON THIS'}",
            f"  cues={self.n_cues}  span={self.span_sec / 60:.1f} min"
            f"  cue_dur median={self.duration_median:.2f}s max={self.duration_max:.2f}s",
            f"  timestamps on whole seconds: {100 * self.integer_ts_ratio:.1f}%",
        ]
        if self.n_transitions:
            lines.append(
                f"  inter-cue gap: median={self.gap_median:.3f}s sd={self.gap_stdev:.4f}"
                f" min={self.gap_min:.3f} max={self.gap_max:.3f}"
                f"{'  [UNIFORM]' if self.gaps_uniform else ''}"
            )
            lines.append(
                f"  total time in gaps: {self.gap_total_sec / 60:.1f} min"
                f" ({100 * self.gap_fraction:.1f}% of span)"
            )
        lines.append(
            f"  punctuation: {self.terminators_per_1k:.2f} terminators/1k chars, "
            f"{self.terminators_per_cue:.2f} per cue  -> mode: {self.recommended_mode}"
        )
        if self.overlap_count:
            lines.append(f"  overlapping cues: {self.overlap_count}")
        if self.nonmonotonic_count:
            lines.append(f"  out-of-order cues: {self.nonmonotonic_count}")
        for w in self.warnings:
            lines.append(f"  ! {w}")
        return "\n".join(lines)


def analyze_timeline(cues: list[SrtCue]) -> TimelineReport:
    """Measure an SRT timeline for signs that it was fabricated.

    Pure: reads no audio and touches no disk. Use :func:`probe_gap_audio` to add
    the decisive speech-in-gaps evidence when the audio is available.
    """
    rep = TimelineReport(n_cues=len(cues))
    if not cues:
        rep.verdict = VERDICT_DEGENERATE
        rep.warnings.append("no cues parsed")
        return rep

    bounds: list[float] = []
    for c in cues:
        bounds.append(c.start_sec)
        bounds.append(c.end_sec)
    on_grid = sum(1 for t in bounds if abs(t - round(t)) < _GRID_EPS)
    rep.integer_ts_ratio = on_grid / len(bounds)

    durations = [c.duration for c in cues]
    rep.duration_median = median(durations)
    rep.duration_max = max(durations)
    rep.span_sec = max(c.end_sec for c in cues) - min(c.start_sec for c in cues)

    # Punctuation density decides whether sentence segmentation is possible at all,
    # and which mode can reach the boundaries. Cheap to measure, and it predicts a
    # failure that otherwise only shows up after a full alignment pass.
    terminators = "।॥?!."
    n_term = sum(c.text.count(t) for c in cues for t in terminators)
    n_chars = sum(len(c.text) for c in cues)
    rep.terminators_per_1k = 1000.0 * n_term / n_chars if n_chars else 0.0
    rep.terminators_per_cue = n_term / len(cues)

    gaps: list[float] = []
    for a, b in zip(cues, cues[1:]):
        gap = b.start_sec - a.end_sec
        if gap < -1e-6:
            rep.overlap_count += 1
        if b.start_sec < a.start_sec:
            rep.nonmonotonic_count += 1
        gaps.append(gap)

    rep.n_transitions = len(gaps)
    if gaps:
        positive = [g for g in gaps if g > 0]
        rep.gap_median = median(gaps)
        rep.gap_stdev = pstdev(gaps) if len(gaps) > 1 else 0.0
        rep.gap_min = min(gaps)
        rep.gap_max = max(gaps)
        rep.gap_total_sec = sum(positive)
        rep.gaps_uniform = (
            len(gaps) >= _MIN_TRANSITIONS_FOR_UNIFORMITY
            and rep.gap_stdev < _UNIFORM_GAP_STDEV
            and rep.gap_median > 0.05
        )

    # --- verdict ---------------------------------------------------------
    if rep.nonmonotonic_count or rep.overlap_count > 0.05 * max(1, rep.n_transitions):
        rep.verdict = VERDICT_DEGENERATE
        rep.warnings.append(
            f"{rep.nonmonotonic_count} out-of-order and {rep.overlap_count} overlapping cues"
        )
    elif rep.gaps_uniform and rep.gap_median >= _SUSPICIOUS_GAP_SEC:
        rep.verdict = VERDICT_SYNTHETIC
        rep.warnings.append(
            f"every one of {rep.n_transitions} gaps is {rep.gap_median:.3f}s "
            f"(sd={rep.gap_stdev:.5f}) - this timeline was generated on a fixed "
            f"grid, not measured against the audio"
        )
        rep.warnings.append(
            f"cutting on it discards {rep.gap_total_sec / 60:.1f} min of audio; if that "
            f"audio contains speech, every clip's text overruns its waveform"
        )
    elif rep.integer_ts_ratio > 0.9:
        rep.verdict = VERDICT_QUANTIZED
        rep.warnings.append(
            f"{100 * rep.integer_ts_ratio:.0f}% of timestamps sit exactly on whole "
            f"seconds - real alignment produces fractional times"
        )

    if rep.verdict == VERDICT_NATURAL and rep.gap_fraction > 0.10:
        rep.warnings.append(
            f"{100 * rep.gap_fraction:.0f}% of the span falls between cues and would "
            f"be discarded - consider close_gaps() or forced alignment"
        )

    if not rep.sentence_segmentable:
        rep.warnings.append(
            f"only {rep.terminators_per_1k:.2f} sentence terminators per 1000 chars "
            f"(healthy Hindi narration: 15-18). This transcript CANNOT be split into "
            f"sentences by any mode - forced alignment will produce accurate timings for "
            f"text that still has no boundaries. Restore punctuation or exclude the source."
        )
    elif rep.terminators_per_cue > 1.2:
        rep.warnings.append(
            f"{rep.terminators_per_cue:.2f} terminators per cue - sentences are SHORTER "
            f"than cues, so cue-level merging cannot reach most boundaries. Use "
            f"mode=aligned_words."
        )
    return rep


def close_gaps(
    cues: list[SrtCue],
    *,
    max_close_seconds: float = 2.0,
) -> tuple[list[SrtCue], float]:
    """Extend each cue's end to the next cue's start, reclaiming inter-cue audio.

    Correct when the gaps are an artifact of a regenerated timeline over
    *continuous* speech: the text of cue N was written for the speech running up
    to cue N+1, so stopping the cut at ``cue.end_sec`` truncates the waveform
    relative to its own transcript.

    Gaps wider than ``max_close_seconds`` are left alone — those are plausibly
    real pauses (scene breaks, music beds), and swallowing them would attach
    unlabelled audio to the clip.

    Returns the rewritten cues and the number of seconds reclaimed. Never
    mutates the input.
    """
    if not cues:
        return [], 0.0

    out: list[SrtCue] = []
    reclaimed = 0.0
    for i, cue in enumerate(cues):
        end = cue.end_sec
        if i + 1 < len(cues):
            gap = cues[i + 1].start_sec - cue.end_sec
            if 0 < gap <= max_close_seconds:
                end = cues[i + 1].start_sec
                reclaimed += gap
        out.append(SrtCue(index=cue.index, start_sec=cue.start_sec, end_sec=end, text=cue.text))
    return out, reclaimed


def probe_gap_audio(
    audio_path: Path,
    cues: list[SrtCue],
    *,
    sample_n: int = 200,
    seed: int = 0,
) -> dict:
    """Decide whether the inter-cue gaps contain speech or silence.

    This is the measurement that separates "the timeline is conservative" from
    "the timeline is fabricated and we are deleting speech". Compares RMS energy
    in gap windows against the interior of their neighbouring cues.

    Imports numpy/soundfile lazily so the rest of this module stays dependency-free
    and unit-testable without audio.

    Returns a dict with ``gap_ratio`` (gap RMS / cue RMS, median), ``speech_frac``
    (share of gaps at >50% of cue loudness) and ``verdict``.
    """
    import random

    import numpy as np
    import soundfile as sf

    info = sf.info(str(audio_path))
    sr = info.samplerate

    def rms(a: float, b: float) -> float:
        a = max(0.0, a)
        n = int((b - a) * sr)
        if n <= 0:
            return 0.0
        x, _ = sf.read(str(audio_path), start=int(a * sr), frames=n, dtype="float32", always_2d=True)
        return float(np.sqrt(np.mean(x[:, 0] ** 2)) + 1e-12)

    transitions = [i for i in range(len(cues) - 1) if cues[i + 1].start_sec > cues[i].end_sec]
    if not transitions:
        return {"gap_ratio": 0.0, "speech_frac": 0.0, "n": 0, "verdict": "no_gaps"}

    rng = random.Random(seed)
    picks = sorted(rng.sample(transitions, min(sample_n, len(transitions))))

    cue_rms, gap_rms = [], []
    for i in picks:
        c = cues[i]
        # Sample the cue interior, away from its own edges.
        inset = min(0.5, c.duration / 4)
        cue_rms.append(rms(c.start_sec + inset, c.end_sec - inset))
        gap_rms.append(rms(c.end_sec, cues[i + 1].start_sec))

    cue_arr = np.array(cue_rms)
    gap_arr = np.array(gap_rms)
    cue_med = float(np.median(cue_arr))
    ratio = float(np.median(gap_arr) / cue_med) if cue_med > 0 else 0.0
    speech_frac = float((gap_arr > 0.5 * cue_med).mean()) if cue_med > 0 else 0.0

    verdict = "speech_in_gaps" if speech_frac > 0.5 else ("silence" if speech_frac < 0.1 else "mixed")
    return {
        "n": len(picks),
        "cue_rms_db": float(20 * np.log10(cue_med)) if cue_med > 0 else float("-inf"),
        "gap_rms_db": float(20 * np.log10(np.median(gap_arr))) if np.median(gap_arr) > 0 else float("-inf"),
        "gap_ratio": ratio,
        "speech_frac": speech_frac,
        "verdict": verdict,
    }
